[project]
name = "st-montecarlo-simulation-m7"
version = "0.1.0"
description = "Simple MonteCarlo Simulation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numba>=0.61.2",
    "numpy>=2.2.6",
    "pandas>=2.3.2",
    "streamlit>=1.49.0",
]
